# This workflow will run tests and build the docker container

name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  install-and-test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/docker-compose.yml') }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint & Prettier
        run: |
          yarn prettier
          yarn lint

      - name: Unit Tests
        run: yarn run test:ci

      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage

      - name: Build & Package
        run: yarn run build
